// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMx6PFde22mBcw4fYZcg6CMl-FEQ2afqk',
    appId: '1:352328752202:web:6caa622936ce82a24c9ab3',
    messagingSenderId: '352328752202',
    projectId: 'bloc-notes-app-1965a',
    authDomain: 'bloc-notes-app-1965a.firebaseapp.com',
    storageBucket: 'bloc-notes-app-1965a.firebasestorage.app',
    measurementId: 'G-91XXYVFJM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9z4D8xy3WudYWA9_GORmH1FH9QFf-GBs',
    appId: '1:352328752202:android:d730fd11767808434c9ab3',
    messagingSenderId: '352328752202',
    projectId: 'bloc-notes-app-1965a',
    storageBucket: 'bloc-notes-app-1965a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC95RK8-5m_v-BWaqULuZOMqxmZAIqHyE',
    appId: '1:352328752202:ios:98a1f039c85b21294c9ab3',
    messagingSenderId: '352328752202',
    projectId: 'bloc-notes-app-1965a',
    storageBucket: 'bloc-notes-app-1965a.firebasestorage.app',
    iosBundleId: 'com.example.blocNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC95RK8-5m_v-BWaqULuZOMqxmZAIqHyE',
    appId: '1:352328752202:ios:98a1f039c85b21294c9ab3',
    messagingSenderId: '352328752202',
    projectId: 'bloc-notes-app-1965a',
    storageBucket: 'bloc-notes-app-1965a.firebasestorage.app',
    iosBundleId: 'com.example.blocNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMx6PFde22mBcw4fYZcg6CMl-FEQ2afqk',
    appId: '1:352328752202:web:556205b84f1a9efc4c9ab3',
    messagingSenderId: '352328752202',
    projectId: 'bloc-notes-app-1965a',
    authDomain: 'bloc-notes-app-1965a.firebaseapp.com',
    storageBucket: 'bloc-notes-app-1965a.firebasestorage.app',
    measurementId: 'G-MQMW8ZZJ5W',
  );
}
